server:
  port: 8096

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path= /users/**

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path= /products/**

        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path= /cart/**

        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path= /order/**

        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path= /payment/**